# Pre-commit Hooks f체r Code-Qualit채t
# Installation: pip install pre-commit && pre-commit install
# Manuell ausf체hren: pre-commit run --all-files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ['-i']
        files: \.(c|cpp|h|hpp|ino)$

  - repo: local
    hooks:
      - id: check-secrets
        name: Pr체fe auf hardcodierte Secrets
        language: system
        entry: bash -c 'if grep -r "WIFI_PASSWORD.*=" --include="*.cpp" src/; then echo "FEHLER - Hardcodierte Passwords gefunden"; exit 1; fi'
        pass_filenames: false
