name: Build Firmware

on:
  push:
    branches: [ main, feat/*, fix/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - esp32-c3-devkitm-1
          - esp32-c3-veml7700
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          .pio
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Create secrets.h from example
      run: |
        cp include/secrets.h.example include/secrets.h
    
    - name: Build ${{ matrix.environment }}
      run: pio run -e ${{ matrix.environment }}
    
    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.environment }}
        path: .pio/build/${{ matrix.environment }}/firmware.bin
        retention-days: 30
